# pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: troubleshooter
  namespace: default
spec:
  containers:
    - name: ephemeral-container
      image: rfinland/ephemeral-container:latest
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
