apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
  initContainers:
    - name: init-ephemeral
      image: ghcr.io/rfatolahzade/ephemeral-container:latest
      command: ["/bin/bash"]
      args: ["-c", "echo 'replace-me-with-your-command'"]
  imagePullSecrets:
    - name: regcred
